### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by stahlmanDesign** [roman01la/impact-node#2]
When I made a basic level with an 8 x 8 tile, and made the mape size 200 x 350, it caused a "too large" error. Making it smaller allowed me to save. When I added tiles and layers, I got the "too large" error again.

Error: request entity too large
    at makeError (/usr/local/lib/node_modules/impact-node/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
    at module.exports (/usr/local/lib/node_modules/impact-node/node_modules/body-parser/node_modules/raw-body/index.js:40:15)
    at read (/usr/local/lib/node_modules/impact-node/node_modules/body-parser/lib/read.js:64:3)
    at Object.urlencodedParser [as handle](/usr/local/lib/node_modules/impact-node/node_modules/body-parser/lib/types/urlencoded.js:104:5)
    at next (/usr/local/lib/node_modules/impact-node/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Object.expressInit [as handle](/usr/local/lib/node_modules/impact-node/node_modules/express/lib/middleware.js:30:5)
    at next (/usr/local/lib/node_modules/impact-node/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Object.query [as handle](/usr/local/lib/node_modules/impact-node/node_modules/express/node_modules/connect/lib/middleware/query.js:43:5)
    at next (/usr/local/lib/node_modules/impact-node/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Function.app.handle (/usr/local/lib/node_modules/impact-node/node_modules/express/node_modules/connect/lib/proto.js:182:3)

**Comment by roman01la** [comment]
Checking...

**Comment by roman01la** [comment]
Ok, I've increased request size up to 5mb. Should work now for really big maps!
Install update: `npm i -g impact-node` and let me know if it works for you now.

**Comment by stahlmanDesign** [comment]
I updated using npm update -g impact-node and it now seems to allow bigger maps. Thanks. I'm not familiar with "npm i" command.

**Comment by roman01la** [comment]
`i` is a shorthand for `install`
